name: Lint

on:
  pull_request:
  push:

permissions: { }

jobs:
  check:
    name: Lint checks
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v5
      - name: Check gawk files
        run: gawk --lint=no-ext -f misc/default-environment-variables.gawk --sandbox /dev/null
      - name: Check Markdown files
        run: npm install markdownlint-cli2 --global && markdownlint-cli2
      - name: Check run scripts
        uses: ./
      - name: Check shell scripts
        run: find . -name '*.sh' -print -execdir shellcheck --check-sourced --enable=all --external-sources --norc {} +
      - name: Check YAML files
        run: yamllint --strict .
